services:
  node-exporter:
    container_name: "node-exporter"
    image: "prom/node-exporter"
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"

  telegraf:
    env_file: [.env]
    container_name: telegraf-vpn
    image: telegraf
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    user: "0:0"
    security_opt:
      - seccomp=unconfined
    environment:
      - INFLUXDB_NETWORK=${INFLUXDB_NETWORK}
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /etc/wireguard:/etc/wireguard:ro
