services:
  docker-proxy:
    container_name: "docker-proxy"
    image: "tecnativa/docker-socket-proxy:latest":
    restart: unless-stopped
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=info
      - CONTAINERS=1
      - EVENTS=1
      - PING=1
      - INFO=1

  node-exporter:
    container_name: "node-exporter"
    image: "prom/node-exporter"
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"

  wgexporter:
    image: mindflavor/prometheus-wireguard-exporter:latest
    container_name: wgexporter
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    user: "0:0"
    command: ["-i","wg0","-d","true"]

